stages:
  - build
  - test

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Project Building
          command: echo "Project Building"
  jobs:
    build:
      steps:
        run:
        - echo "Running SAST"
        - curl -sSL https://cli.kondukto.io | sh
        - export KONDUKTO_HOST=$KONDUKTO_HOST
        - export KONDUKTO_TOKEN=$KONDUKTO_TOKEN
        - kdt scan -p jusiceshopcircleci -t gosec -b master